namespace FastSharp.Modules.Configuration;

/// <summary>
/// Identifies the individual CRUD endpoints generated by FastSharp.
/// Used with <see cref="ICrudEndpoints{TDbContext}.DisableEndpoint"/> to selectively disable routes.
/// </summary>
public enum GenericEndpoint
{
    /// <summary>The GET endpoint that returns a list of entities (with optional pagination).</summary>
    GetList,
    /// <summary>The GET endpoint that returns a single entity by its primary key.</summary>
    GetById,
    /// <summary>The POST endpoint that creates a new entity.</summary>
    Create,
    /// <summary>The PUT endpoint that replaces an existing entity.</summary>
    Update,
    /// <summary>The DELETE endpoint that removes an entity by its primary key.</summary>
    Delete,
    /// <summary>Targets all five generated endpoints at once.</summary>
    All
}
