using FastSharp.Models;
using Microsoft.EntityFrameworkCore;

namespace FastSharp.Modules.Configuration;

/// <summary>
/// Provides a fluent API for configuring the CRUD endpoints generated by FastSharp.
/// An instance of this interface is passed to the <c>configure</c> delegate in
/// <see cref="Core.Module{TDbContext}.AddCRUD{TEntity, TKey}(string, System.Action{ICrudEndpoints{TDbContext}})"/>.
/// </summary>
/// <typeparam name="TDbContext">The Entity Framework <see cref="DbContext"/> backing the generated endpoints.</typeparam>
public interface ICrudEndpoints<TDbContext> where TDbContext : DbContext
{
    /// <summary>
    /// Disables the specified generic endpoint, preventing it from being registered as a route for incoming requests so you can make your own implementation or simply not using it.
    /// </summary>
    /// <param name="endpointName">The generic endpoint to disable. This parameter must not be null.</param>
    public void DisableEndpoint(GenericEndpoint endpointName);

    /// <summary>
    /// Configures all CRUD endpoints with the specified action on each endpoint's route handler builder.
    /// </summary>
    /// <remarks>
    /// This allows shared metadata (e.g. authorization, validation) to be applied to every generated CRUD endpoint
    /// without requiring a DTO. Note that this overload does not replace endpoint types — it only decorates them.
    /// </remarks>
    /// <param name="configure">An action that configures each endpoint's RouteHandlerBuilder.</param>
    public void ConfigureAll(Action<RouteHandlerBuilder> configure);

    /// <summary>
    /// Configures all CRUD endpoints to use a single DTO type.
    /// </summary>
    /// <remarks>
    /// The provided <typeparamref name="TDto"/> is used as the contract for GetById, GetList,
    /// Create, and Update endpoints.
    /// For list endpoints, the framework wraps the DTO automatically as <see cref="List{TDto}"/>
    /// and when <c>page</c>/<c>pageSize</c> query params are provided, as <see cref="PagedResult{TDto}"/>.
    /// </remarks>
    /// <typeparam name="TDto">The DTO type used for all CRUD endpoints.</typeparam>
    /// <param name="configure">Optional endpoint configuration applied to all mapped CRUD handlers.</param>
    public void ConfigureAll<TDto>(Action<RouteHandlerBuilder>? configure = null) where TDto : class;

    /// <summary>
    /// Configures CRUD endpoints with different request and response DTO types.
    /// </summary>
    /// <remarks>
    /// <typeparamref name="TResponse"/> is used for GetById, GetList responses.
    /// <typeparamref name="TRequest"/> is used for Create and Update request bodies.
    /// Create returns <typeparamref name="TResponse"/>.
    /// For list endpoints, FastSharp wraps <typeparamref name="TResponse"/> automatically
    /// as <see cref="List{TResponse}"/>, and when <c>page</c>/<c>pageSize</c> query params are provided,
    /// as <see cref="PagedResult{TResponse}"/>.
    /// </remarks>
    /// <typeparam name="TRequest">The DTO type used for write operations.</typeparam>
    /// <typeparam name="TResponse">The DTO type used for read operations.</typeparam>
    /// <param name="configure">Optional endpoint configuration applied to all mapped CRUD handlers.</param>
    public void ConfigureAll<TRequest, TResponse>(Action<RouteHandlerBuilder>? configure = null) where TRequest : class where TResponse : class;

    /// <summary>
    /// Configures the route group using the specified configuration action for all the endpoints of the generic CRUD.
    /// </summary>
    /// <remarks>This method allows for the customization of route groups, enabling developers to define
    /// specific routing behaviors and settings.
    /// settings.</remarks>
    /// <param name="configure">An optional action that configures the route group. If provided, it receives a RouteGroupBuilder instance to
    /// define the routes within the group.</param>
    public void ConfigureGroup(Action<RouteGroupBuilder>? configure = null);

    /// <summary>Configures the GET by id endpoint without changing its response type.</summary>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Get(Action<RouteHandlerBuilder>? configure = null);

    /// <summary>Configures the GET by id endpoint to map the entity to <typeparamref name="TDto"/> before returning.</summary>
    /// <typeparam name="TDto">The response DTO type.</typeparam>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Get<TDto>(Action<RouteHandlerBuilder>? configure = null) where TDto : class;

    /// <summary>Configures the GET list endpoint without changing its response type.</summary>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void GetList(Action<RouteHandlerBuilder>? configure = null);

    /// <summary>
    /// Configures the GetList endpoint and overrides the maximum page size for this endpoint only.
    /// </summary>
    /// <remarks>
    /// The override takes precedence over the global <see cref="FastSharpOptions.MaxPageSize"/>.
    /// It caps the number of rows returned when no pagination parameters are supplied and acts as the
    /// upper bound for the <c>pageSize</c> query parameter.
    /// </remarks>
    /// <param name="maxPageSize">The maximum page size for this endpoint. Values below 1 are treated as 1.</param>
    /// <param name="configure">An optional delegate to further configure the route.</param>
    public void GetList(int maxPageSize, Action<RouteHandlerBuilder>? configure = null);

    /// <summary>
    /// By default returns <see cref="List{TEntity}"/>. When <c>page</c> and/or <c>pageSize</c>
    /// query parameters are provided, returns <see cref="PagedResult{TEntity}"/> instead.
    /// </summary>
    /// <param name="configure">An optional delegate to further configure the route using the provided RouteHandlerBuilder. If null, the route
    /// is added with default configuration.</param>
    public void GetList<TDto>(Action<RouteHandlerBuilder>? configure = null) where TDto : class;

    /// <summary>
    /// Configures the GetList endpoint with a DTO contract and overrides the maximum page size for
    /// this endpoint only. The override takes precedence over the global <see cref="FastSharpOptions.MaxPageSize"/>.
    /// </summary>
    /// <typeparam name="TDto">The DTO type returned by the list endpoint.</typeparam>
    /// <param name="maxPageSize">The maximum page size for this endpoint. Values below 1 are treated as 1.</param>
    /// <param name="configure">An optional delegate to further configure the route.</param>
    public void GetList<TDto>(int maxPageSize, Action<RouteHandlerBuilder>? configure = null) where TDto : class;

    /// <summary>Configures the POST endpoint without changing its request or response types.</summary>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Create(Action<RouteHandlerBuilder>? configure = null);

    /// <summary>Configures the POST endpoint to use <typeparamref name="TDto"/> for both the request body and the response.</summary>
    /// <typeparam name="TDto">The DTO type used for the request body and the created-entity response.</typeparam>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Create<TDto>(Action<RouteHandlerBuilder>? configure = null) where TDto : class;

    /// <summary>Configures the POST endpoint with separate request and response DTO types.</summary>
    /// <typeparam name="TRequest">The DTO type used for the request body.</typeparam>
    /// <typeparam name="TResponse">The DTO type returned after the entity is created.</typeparam>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Create<TRequest, TResponse>(Action<RouteHandlerBuilder>? configure = null) where TRequest : class where TResponse : class;

    /// <summary>Configures the PUT endpoint without changing its request type.</summary>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Update(Action<RouteHandlerBuilder>? configure = null);

    /// <summary>Configures the PUT endpoint to use <typeparamref name="TDto"/> as the request body.</summary>
    /// <typeparam name="TDto">The DTO type used for the request body.</typeparam>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Update<TDto>(Action<RouteHandlerBuilder>? configure = null) where TDto : class;

    /// <summary>Configures the DELETE endpoint.</summary>
    /// <param name="configure">An optional delegate to further configure the route handler.</param>
    public void Delete(Action<RouteHandlerBuilder>? configure = null);
    internal void Map(RouteGroupBuilder group, ILogger logger, string moduleRoutePrefix);
}
