using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace FastSharp.Generators;

[Generator]
public sealed class FastSharpEndpointDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntaxContext, _) => GetCandidate(syntaxContext))
            .Where(static candidate => candidate is not null)!;

        var compilationAndCandidates = context.CompilationProvider.Combine(typeDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (spc, source) => Execute(spc, source.Left, source.Right));
    }

    private static CandidateInfo? GetCandidate(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.IsAbstract)
        {
            return null;
        }

        return new CandidateInfo(
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<CandidateInfo?> rawCandidates)
    {
        var endpointInterface = compilation.GetTypeByMetadataName("FastSharp.Modules.IEndpoint");
        var moduleInterface = compilation.GetTypeByMetadataName("FastSharp.Modules.IFastModule");
        var registryInterface = compilation.GetTypeByMetadataName("FastSharp.Modules.Registry.IFastSharpAssemblyRegistry");
        var registryStore = compilation.GetTypeByMetadataName("FastSharp.Modules.Registry.FastSharpAssemblyRegistryStore");
        var moduleInvoker = compilation.GetTypeByMetadataName("FastSharp.Modules.Registry.FastSharpModuleInvoker");

        if (endpointInterface is null || moduleInterface is null || registryInterface is null || registryStore is null || moduleInvoker is null)
        {
            return;
        }

        var candidates = rawCandidates
            .Where(static candidate => candidate is not null)
            .Select(static candidate => candidate!)
            .Distinct(CandidateInfoComparer.Instance)
            .ToArray();

        var endpoints = new List<CandidateInfo>();
        var modules = new List<CandidateInfo>();

        foreach (var candidate in candidates)
        {
            var symbol = compilation.GetTypeByMetadataName(NormalizeMetadataName(candidate.FullyQualifiedName));
            if (symbol is null)
            {
                continue;
            }

            if (Implements(symbol, endpointInterface))
            {
                endpoints.Add(candidate);
            }

            if (Implements(symbol, moduleInterface))
            {
                modules.Add(candidate);
            }
        }

        var source = BuildSource(endpoints, modules);
        context.AddSource("FastSharpAssemblyRegistry.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static bool Implements(INamedTypeSymbol symbol, INamedTypeSymbol contract)
    {
        return symbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, contract));
    }

    private static string NormalizeMetadataName(string fullyQualifiedName)
    {
        return fullyQualifiedName.Replace("global::", string.Empty);
    }

    private static string BuildSource(IReadOnlyList<CandidateInfo> endpoints, IReadOnlyList<CandidateInfo> modules)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace FastSharp.Modules.Registry;");
        sb.AppendLine();
        sb.AppendLine("internal static class FastSharpGeneratedAssemblyRegistryInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        FastSharpAssemblyRegistryStore.Register(new FastSharpGeneratedAssemblyRegistry());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal sealed class FastSharpGeneratedAssemblyRegistry : IFastSharpAssemblyRegistry");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly Assembly CurrentAssembly = typeof(FastSharpGeneratedAssemblyRegistry).Assembly;");
        sb.AppendLine("    private static readonly Type[] EndpointTypes =");
        sb.AppendLine("    [");
        foreach (var endpoint in endpoints.OrderBy(static e => e.FullyQualifiedName, StringComparer.Ordinal))
        {
            sb.AppendLine($"        typeof({endpoint.FullyQualifiedName}),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    private static readonly Type[] ModuleTypes =");
        sb.AppendLine("    [");
        foreach (var module in modules.OrderBy(static m => m.FullyQualifiedName, StringComparer.Ordinal))
        {
            sb.AppendLine($"        typeof({module.FullyQualifiedName}),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    public Assembly Assembly => CurrentAssembly;");
        sb.AppendLine();
        sb.AppendLine("    public void RegisterServices(IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var endpointType in EndpointTypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            services.AddTransient(endpointType);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var moduleType in ModuleTypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            services.AddTransient(moduleType);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void MapEndpoints(IEndpointRouteBuilder app)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var moduleType in ModuleTypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            FastSharpModuleInvoker.Map(app, moduleType);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public IReadOnlyList<Type> GetEndpointTypes(string namespacePrefix)");
        sb.AppendLine("    {");
        sb.AppendLine("        return EndpointTypes");
        sb.AppendLine("            .Where(type => type.Namespace is not null && type.Namespace.StartsWith(namespacePrefix, StringComparison.Ordinal))");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class CandidateInfo(string fullyQualifiedName, string @namespace)
    {
        public string FullyQualifiedName { get; } = fullyQualifiedName;

        public string Namespace { get; } = @namespace;
    }

    private sealed class CandidateInfoComparer : IEqualityComparer<CandidateInfo>
    {
        public static CandidateInfoComparer Instance { get; } = new();

        public bool Equals(CandidateInfo? x, CandidateInfo? y)
        {
            return StringComparer.Ordinal.Equals(x?.FullyQualifiedName, y?.FullyQualifiedName);
        }

        public int GetHashCode(CandidateInfo obj)
        {
            return StringComparer.Ordinal.GetHashCode(obj.FullyQualifiedName);
        }
    }
}
