name: Publish NuGet packages

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    environment: nuget
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: |
          #Sacamos la versión aquí para que el Build ya la tenga
          VERSION=${GITHUB_REF_NAME#v}
          dotnet build -c Release --no-restore /p:Version=$VERSION

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack
        run: |
          # Extraemos el número de versión (quitando la 'v')
          VERSION=${GITHUB_REF_NAME#v}

          dotnet pack FastSharp.Models/FastSharp.Models.csproj -c Release -o ./artifacts --no-build /p:Version=$VERSION
          dotnet pack FastSharp.Modules/FastSharp.Modules.csproj -c Release -o ./artifacts --no-build /p:Version=$VERSION
          dotnet pack FastSharp.Templates/FastSharp.Templates.csproj -c Release -o ./artifacts --no-build /p:Version=$VERSION

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
         user: ${{ secrets.NUGET_USERNAME }}

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate